import { IModKit, ValidationMessageGroup } from '../../../interfaces';
import { countExistingLoreScrolls, generateLoreScrolls } from '../autocontent';

export function checkAutogenerated(mod: IModKit): ValidationMessageGroup {
  // check npc dialog refs, make sure they exist
  const autoValidations: ValidationMessageGroup = {
    header: `Autogenerated Content`,
    messages: [],
  };

  const existingLore = countExistingLoreScrolls(mod);
  const allAvailableLore = generateLoreScrolls(mod);

  if (allAvailableLore.length !== existingLore) {
    autoValidations.messages.push({
      type: 'error',
      message: `Outdated number of lore scrolls found: the mod has ${existingLore} but there are ${allAvailableLore.length} available.`,
    });
  }

  return autoValidations;
}
