import { IModKit, ValidationMessageGroup } from '../../../interfaces';
import {
  countExistingLoreScrolls,
  countExistingTraitScrolls,
  generateLoreScrolls,
  generateTraitScrolls,
} from '../autocontent';

export function checkAutogenerated(mod: IModKit): ValidationMessageGroup {
  // check npc dialog refs, make sure they exist
  const autoValidations: ValidationMessageGroup = {
    header: `Autogenerated Content`,
    messages: [],
  };

  const existingLore = countExistingLoreScrolls(mod);
  const allAvailableLore = generateLoreScrolls(mod);

  if (allAvailableLore.length !== existingLore) {
    autoValidations.messages.push({
      type: 'error',
      message: `Outdated number of lore scrolls found: the mod has ${existingLore} but there are ${allAvailableLore.length} available.`,
    });
  }

  const existingRuneScrolls = countExistingTraitScrolls(mod);
  const allAvailableRuneScrolls = generateTraitScrolls(mod);

  if (allAvailableRuneScrolls.length !== existingRuneScrolls) {
    autoValidations.messages.push({
      type: 'error',
      message: `Outdated number of rune scrolls found: the mod has ${existingRuneScrolls} but there are ${allAvailableRuneScrolls.length} available.`,
    });
  }

  return autoValidations;
}
