import { sortBy } from 'lodash';
import {
  BaseClassType,
  IModKit,
  ModJSON,
  ValidationMessageGroup,
} from '../../interfaces';
import {
  checkAutogenerated,
  checkItemStats,
  checkItemUses,
  checkMapBGMs,
  checkMapItems,
  checkMapNPCDialogs,
  checkMapObjects,
  checkMapProperties,
  checkMapSpawners,
  checkMapTeleports,
  checkNPCs,
  checkNPCUsages,
  checkQuests,
  checkRecipes,
  checkSpawners,
  nonexistentItems,
  nonexistentNPCs,
  nonexistentRecipes,
  validateAchievements,
  validateDialogActions,
  validateDialogs,
  validateDialogsItems,
  validateDroptables,
  validateEvents,
  validateItems,
  validateNPCs,
  validateQuests,
  validateRecipes,
  validateRNGDungeons,
  validateSpawners,
  validateTraitTreeData,
  validateTraitTrees,
} from './validators';
import { validateSTEMProperties, validateSTEMs } from './validators/stem';

export function validationMessagesForMod(
  mod: IModKit,
  classes: BaseClassType[],
  json: ModJSON
): ValidationMessageGroup[] {
  const validationContainer: ValidationMessageGroup[] = [
    checkItemStats(mod),
    checkItemUses(mod),
    checkMapNPCDialogs(mod),
    checkNPCUsages(mod),
    checkNPCs(mod),
    checkRecipes(mod),
    checkSpawners(mod),
    checkQuests(mod),
    ...checkMapBGMs(mod, json),
    ...checkMapProperties(mod),
    ...checkMapTeleports(mod),
    ...checkMapSpawners(mod),
    ...checkMapItems(mod),
    ...checkMapObjects(mod),
    validateEvents(mod),
    validateDialogs(mod),
    validateDialogActions(mod),
    validateDialogsItems(mod, classes),
    validateTraitTrees(mod),
    validateTraitTreeData(mod, classes),
    validateItems(mod),
    validateDroptables(mod),
    validateNPCs(mod),
    validateQuests(mod),
    validateRecipes(mod),
    validateSpawners(mod),
    validateSTEMs(mod),
    validateSTEMProperties(mod),
    validateRNGDungeons(mod, classes),
    validateAchievements(mod),
    nonexistentItems(mod),
    nonexistentNPCs(mod),
    nonexistentRecipes(mod),
    checkAutogenerated(mod),
  ];

  validationContainer.forEach((v) => {
    v.messages = sortBy(v.messages, 'message');
  });

  validationContainer.forEach((v) => {
    if (v.messages.length !== 0) return;

    v.messages.push({
      type: 'good',
      message: 'No abnormalities!',
    });
  });

  return sortBy(validationContainer, 'header');
}

export function numErrorsForMod(
  mod: IModKit,
  classes: BaseClassType[],
  json: ModJSON
): number {
  const validationMessages = validationMessagesForMod(mod, classes, json);

  const numErrors = validationMessages
    .map((v) => v.messages)
    .flat()
    .filter((vdn) => vdn.type === 'error').length;

  return numErrors;
}
