import { isArray, isBoolean, isNumber, isObject, isString } from 'lodash';
import { DialogActionType, Schema } from '../../../interfaces';
import {
  is,
  isAny,
  isArrayOf,
  isCurrency,
  isDialogChatOption,
  isDialogItem,
  isDialogItemSlot,
  isHoliday,
} from './_helpers';

export const dialogBehaviorSchemas: Record<DialogActionType, Schema> = {
  [DialogActionType.Chat]: [
    ['type', true, is('chat')],
    ['displayNPCSprite', false, isNumber],
    ['displayNPCName', false, isString],
    ['displayNPCUUID', false, isString],
    ['displayItemName', false, isString],
    ['displayNPCSprite', false, isNumber],
    ['displayTitle', false, isString],
    ['maxDistance', false, isNumber],
    ['message', true, isString],
    ['width', false, isString],
    ['extraClasses', false, isArrayOf(isString)],
    ['options', false, isArrayOf(isDialogChatOption)],
  ],
  [DialogActionType.CheckItem]: [
    ['type', true, is('checkItem')],
    ['maxDistance', false, isNumber],
    ['fromHands', false, isBoolean],
    ['fromSack', false, isBoolean],
    ['checkProperty', false, isString],
    ['checkValue', false, isAny],
    ['slot', true, isDialogItemSlot],
    ['item', true, isDialogItem],
    ['checkFailActions', false, isArray],
    ['checkPassActions', true, isArray],
  ],
  [DialogActionType.CheckNoItem]: [
    ['type', true, is('checkNoItem')],
    ['maxDistance', false, isNumber],
    ['fromHands', false, isBoolean],
    ['slot', true, isArrayOf(isDialogItemSlot)],
    ['checkFailActions', false, isArray],
    ['checkPassActions', true, isArray],
  ],
  [DialogActionType.TakeItem]: [
    ['type', true, is('takeItem')],
    ['maxDistance', false, isNumber],
    ['slot', true, isDialogItemSlot],
    ['fromHands', false, isBoolean],
    ['item', true, isDialogItem],
  ],
  [DialogActionType.GiveItem]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('giveItem')],
    ['slot', true, isDialogItemSlot],
    ['item', true, isDialogItem],
  ],
  [DialogActionType.MergeAndGiveItem]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('mergeAndGiveItem')],
    ['slot', true, isDialogItemSlot],
    ['item', true, isDialogItem],
  ],
  [DialogActionType.ModifyItem]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('modifyItem')],
    ['slot', true, isArrayOf(isDialogItemSlot)],
    ['item', false, isDialogItem],
    ['mods', true, isObject],
  ],
  [DialogActionType.CheckItemCanUpgrade]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('checkItemCanUpgrade')],
    ['slot', true, isDialogItemSlot],
    ['upgrade', false, isString],
    ['fromHands', false, isBoolean],
    ['item', false, isDialogItem],
    ['checkFailActions', false, isArray],
    ['checkPassActions', true, isArray],
  ],
  [DialogActionType.AddUpgradeItem]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('addItemUpgrade')],
    ['slot', true, isDialogItemSlot],
    ['upgrade', false, isString],
  ],
  [DialogActionType.GiveEffect]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('giveEffect')],
    ['effect', true, isString],
    ['duration', true, isNumber],
    ['potency', false, isNumber],
  ],
  [DialogActionType.CheckEffect]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('checkEffect')],
    ['effect', true, isString],
    ['maxDistance', false, isNumber],
    ['checkFailActions', false, isArray],
    ['checkPassActions', true, isArray],
  ],
  [DialogActionType.GiveSelfEffect]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('giveSelfEffect')],
    ['effect', true, isString],
    ['duration', true, isNumber],
    ['potency', false, isNumber],
  ],
  [DialogActionType.GiveCurrency]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('giveCurrency')],
    ['currency', true, isCurrency],
    ['amount', true, isNumber],
  ],
  [DialogActionType.CheckQuest]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('checkQuest')],
    ['quest', true, isString],
    ['maxDistance', false, isNumber],
    ['questCompleteActions', false, isArray],
  ],
  [DialogActionType.UpdateQuest]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('updateQuest')],
    ['quest', true, isString],
    ['maxDistance', false, isNumber],
    ['arrayItem', false, isString],
  ],
  [DialogActionType.CheckHoliday]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('checkHoliday')],
    ['holiday', true, isHoliday],
    ['checkFailActions', false, isArray],
    ['checkPassActions', true, isArray],
  ],
  [DialogActionType.CheckDailyQuest]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('checkDailyQuest')],
    ['quests', true, isArrayOf(isString)],
    ['npc', true, isString],
    ['maxDistance', false, isNumber],
  ],
  [DialogActionType.GiveQuest]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('giveQuest')],
    ['quest', true, isString],
    ['maxDistance', false, isNumber],
  ],
  [DialogActionType.HasQuest]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('hasQuest')],
    ['quest', true, isString],
    ['maxDistance', false, isNumber],
    ['checkFailActions', false, isArray],
    ['checkPassActions', true, isArray],
  ],
  [DialogActionType.GiveDailyQuest]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('giveDailyQuest')],
    ['quests', true, isArrayOf(isString)],
    ['maxDistance', false, isNumber],
  ],
  [DialogActionType.CheckLevel]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('checkLevel')],
    ['level', true, isNumber],
    ['checkFailActions', false, isArray],
    ['checkPassActions', true, isArray],
  ],
  [DialogActionType.CheckNPCsAndDropItems]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('checkNearbyNPCsAndDropItems')],
    ['npcs', true, isArrayOf(isString)],
    ['item', true, isString],
    ['checkFailActions', false, isArray],
    ['checkPassActions', true, isArray],
  ],
  [DialogActionType.CheckAnyHostilesNearby]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('checkAnyHostilesNearby')],
    ['range', true, isNumber],
    ['checkFailActions', false, isArray],
    ['checkPassActions', true, isArray],
  ],
  [DialogActionType.DropItems]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('dropItems')],
    ['item', true, isString],
    ['amount', true, isNumber],
  ],
  [DialogActionType.KillSelfSilently]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('killSelfSilently')],
    ['leaveMessage', false, isString],
  ],
  [DialogActionType.GrantAchievement]: [
    ['maxDistance', false, isNumber],
    ['type', true, is('grantAchievement')],
    ['achievementName', true, isString],
  ],
};
