import { isBoolean, isNumber, isObject, isString } from 'lodash';
import { Schema } from '../../../interfaces';
import {
  is2DNumberArray,
  isArrayOf,
  isDamageType,
  isPartialStatObject,
  isPartialStatObjectFailure,
  isStat,
  isStringOrBoolean,
} from './_helpers';

export const stemSchema: Schema = [
  ['name', true, isString],
  ['_gameId', true, isString],

  ['_hasSpell', false, isBoolean],
  ['_hasTrait', false, isBoolean],
  ['_hasEffect', false, isBoolean],
  ['_hasMacro', false, isBoolean],

  ['all', true, isObject],
  ['all.desc', false, isString],
  ['all.icon', false, isString],
  ['all.color', false, isString],
  ['all.bgColor', false, isString],

  ['spell', false, isObject],
  ['spell.spellName', false, isString],
  ['spell.maxSkillForGain', false, isNumber],
  ['spell.mpCost', false, isNumber],
  ['spell.castTime', false, isNumber],
  ['spell.cooldown', false, isNumber],
  ['spell.damageClass', false, isDamageType],
  ['spell.willSaveThreshold', false, isNumber],
  ['spell.willSavePercent', false, isNumber],
  ['spell.potencyMultiplier', false, isNumber],
  ['spell.bonusRollsMin', false, isNumber],
  ['spell.bonusRollsMax', false, isNumber],
  ['spell.skillMultiplierChanges', false, is2DNumberArray],

  ['spell.spellMeta', false, isObject],
  ['spell.spellMeta.aoe', false, isBoolean],
  ['spell.spellMeta.aoeRangeTrait', false, isString],
  ['spell.spellMeta.allowDirectional', false, isBoolean],
  ['spell.spellMeta.bonusAgro', false, isNumber],
  ['spell.spellMeta.canBeResisted', false, isBoolean],
  ['spell.spellMeta.noReflect', false, isBoolean],
  ['spell.spellMeta.staticPotency', false, isBoolean],
  ['spell.spellMeta.creatureSummoned', false, isArrayOf(isString)],
  ['spell.spellMeta.doesHeal', false, isBoolean],
  ['spell.spellMeta.doesAttack', false, isBoolean],
  ['spell.spellMeta.doesOvertime', false, isBoolean],
  ['spell.spellMeta.extraAttackTrait', false, isString],
  ['spell.spellMeta.linkedEffectName', false, isString],
  ['spell.spellMeta.linkedEffectScaleDuration', false, isNumber],
  ['spell.spellMeta.linkedEffectScaleState', false, isStat],
  ['spell.spellMeta.noHostileTarget', false, isBoolean],
  ['spell.spellMeta.casterMessage', false, isString],
  ['spell.spellMeta.casterAttackMessage', false, isString],
  ['spell.spellMeta.casterSfx', false, isString],
  ['spell.spellMeta.targetMessage', false, isString],
  ['spell.spellMeta.targetAttackMessage', false, isString],
  ['spell.spellMeta.targetSfx', false, isString],
  ['spell.spellMeta.targetsParty', false, isBoolean],
  ['spell.spellMeta.range', false, isNumber],
  ['spell.spellMeta.resistLowerTrait', false, isString],
  ['spell.spellMeta.useSkillAsPotency', false, isBoolean],
  ['spell.spellMeta.fizzledBy', false, isArrayOf(isString)],

  ['trait', false, isObject],
  ['trait.name', false, isString],
  ['trait.desc', false, isString],
  ['trait.icon', false, isString],

  ['trait.iconColor', false, isString],
  ['trait.iconBgColor', false, isString],
  ['trait.borderColor', false, isString],

  ['trait.isAncient', false, isBoolean],
  ['trait.valuePerTier', false, isNumber],
  ['trait.spellGiven', false, isString],

  ['trait.statsGiven', false, isPartialStatObject, isPartialStatObjectFailure],

  ['effect', false, isObject],

  ['effect.tooltip', false, isObject],
  ['effect.tooltip.name', false, isString],
  ['effect.tooltip.color', false, isString],
  ['effect.tooltip.bgColor', false, isString],
  ['effect.tooltip.desc', false, isString],
  ['effect.tooltip.icon', false, isString],

  ['effect.effect', false, isObject],
  ['effect.effect.type', false, isString],
  ['effect.effect.duration', false, isNumber],
  ['effect.effect.durationScaleValue', false, isNumber],
  ['effect.effect.durationScaleStat', false, isStat],

  ['effect.effect.extra', false, isObject],
  ['effect.effect.extra.potency', false, isNumber],
  ['effect.effect.extra.canRemove', false, isBoolean],
  ['effect.effect.extra.doesTick', false, isBoolean],
  ['effect.effect.extra.unique', false, isStringOrBoolean],
  ['effect.effect.extra.persistThroughDeath', false, isBoolean],
  ['effect.effect.extra.canOverlapUniqueIfEquipped', false, isBoolean],
  ['effect.effect.extra.charges', false, isNumber],
  [
    'effect.effect.extra.statChanges',
    false,
    isPartialStatObject,
    isPartialStatObjectFailure,
  ],

  ['effect.effectMeta', false, isObject],
  ['effect.effectMeta.effectRef', false, isString],
  ['effect.effectMeta.recentlyRef', false, isString],
  ['effect.effectMeta.castMessage', false, isString],
  ['effect.effectMeta.applyMessage', false, isString],
  ['effect.effectMeta.unapplyMessage', false, isString],
  ['effect.effectMeta.castSfx', false, isString],
  ['effect.effectMeta.applySfx', false, isString],
  ['effect.effectMeta.noStack', false, isBoolean],

  ['macro', false, isObject],
  ['macro.name', false, isString],
  ['macro.tooltipDesc', false, isString],
  ['macro.macro', false, isString],
  ['macro.icon', false, isString],
  ['macro.color', false, isString],
  ['macro.bgColor', false, isString],
  ['macro.mode', false, isString],
  ['macro.key', false, isString],
  ['macro.isDefault', false, isBoolean],
];
