import {
  heroArrowDownOnSquare,
  heroArrowPathRoundedSquare,
  heroArrowsRightLeft,
  heroArrowTopRightOnSquare,
  heroArrowTurnLeftUp,
  heroArrowTurnRightDown,
  heroDocumentDuplicate,
  heroDocumentText,
  heroFaceFrown,
  heroFaceSmile,
  heroFire,
  heroInformationCircle,
  heroMinus,
  heroPencil,
  heroPlus,
  heroTrash,
} from '@ng-icons/heroicons/outline';

export const appIcons = {
  heroArrowDownOnSquare,
  heroDocumentDuplicate,
  heroDocumentText,
  heroPencil,
  heroPlus,
  heroMinus,
  heroTrash,
  heroArrowsRightLeft,
  heroFaceFrown,
  heroFaceSmile,
  heroArrowPathRoundedSquare,
  heroArrowTopRightOnSquare,
  heroInformationCircle,
  heroFire,
  heroArrowTurnLeftUp,
  heroArrowTurnRightDown,
};
